# Generated by Django 4.1.7 on 2023-02-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(choices=[('ICS-P1', 'ICS-Part1'), ('ICS-P2', 'ICS-Part2'), ('M-P1', 'MEDICAL-Part1'), ('M-P2', 'MEDICAL-Part2'), ('NM-P1', 'NON-MEDICAL-Part1'), ('NM-P2', 'NON-MEDICAL-Part2')], max_length=6),
        ),
    ]
