# Generated by Django 4.1.7 on 2023-02-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='join',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
