# Generated by Django 4.1.7 on 2023-02-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pass_matric',
            field=models.BooleanField(default=True),
        ),
    ]
