# Generated by Django 4.1.7 on 2023-02-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacher_teacher_class_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_class',
            field=models.CharField(choices=[('M-P1', 'MEDICAL-PART1'), ('M-P2', 'MEDICAL-PART2'), ('NM-P1', 'NON-MEDICAL-PART2'), ('ICS-P1', 'ICS-PART1'), ('NM-P2', 'NON-MEDICAL-PART2'), ('ICS-P2', 'ICS-PART2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.BigAutoField(default=1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
